### ISSUE TITLE
Allowed datatypes

### ISSUE THREAD

**Issue by lambdaofgod** [ash-project/ash_sqlite#1]
What are the types that can be stored in Sqlite? I've tried to store Maps and Atoms but for example when I have a `:map` attribute I get the following when I try to create a Resource:

```
** (Ash.Error.Unknown) Unknown Error
 
 * ** (FunctionClauseError) no function clause matching in Ecto.Type.process_dumpers/3
```

### Why I need Maps 

I have an application where I want to persist requests to some API. I cannot assume I know the schema because it is subject to change - the simplest way would be to have a `:map` attribute on my resource that represents an API call.

### What would be helpful

- make it possible to store structs/maps
  I believe this might be tricky, but maybe a workaround is possible? I mean in principle it should be doable because we can always use some kind of adapter to store maps as strings in JSON and then save/load them so that the Resource definition actually has Maps 
- throw an error when someone tries to define a `Resource` with fields that cannot be persisted in Sqlite

**Comment by zachdaniel** [comment]
I totally did not see this, sorry! My watch settings weren't on on this repo. I'm surprised that `ecto_sqlite` doesn't support the `:map` type, essentially exactly as you're saying, but I also get it. Typically what we do in that case is we have an adapter type that we overwrite at the data layer to store the values as text. We'd then transform any occurrences of `Ash.Type.Map` to this new thing.

In the meantime, you should be able to define a map type with a storage type of `:text`, or something along those lines. Did you end up finding a workaround? You can also use the `:term` type, which has a storage type of `:binary` and uses Erlang term format. I honestly haven't plumbed the depths of what is/isn't possible with `ecto_sqlite` but I think that could be would be worth exploring.
